---
# Source: demo/templates/demo.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo
---
# Source: demo/templates/demo.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    app: demo
  ports:
  - port: 8080
---
# Source: demo/templates/demo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: "nginx:latest"
